"on":
  push:
    branches:
      - sms/intgtests
name: Deploy to integration-test-provisioning
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Pull unauthenticated images
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker pull ghcr.io/porter-dev/cluster-control-plane/ccp-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.IMAGE_BUILD_TOKEN }}
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply
        env:
          PORTER_CLUSTER: "11"
          PORTER_HOST: https://dashboard.internal-tools.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "8"
          PORTER_STACK_NAME: integration-test-provisioning
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_STACK_8_11 }}
